# .github/workflows/ping-daily-0400.yml
name: Ping Vercel maintenance (daily 04:00 UTC)

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ext-crons-daily
      cancel-in-progress: false
    env:
      BASE_URL: "https://spotify-oauth-min-jonas-sercombes-projects.vercel.app"
    steps:
      - name: Ping /api/watch/cron-maintenance-all
        run: |
          for i in {1..3}; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" "$BASE_URL/api/watch/cron-maintenance-all") || true
            echo "HTTP $CODE"
            [ "$CODE" = "200" ] && exit 0
            sleep 5
          done
          echo "Endpoint returned non-200 after retries"; exit 1
