# .github/workflows/ping-daily-0400.yml
name: Ping Vercel maintenance (daily 04:00 UTC)
on:
  schedule: [ { cron: "0 4 * * *" } ]
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BASE_URL: "https://spotify-oauth-min-jonas-sercombes-projects.vercel.app"
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    steps:
      - name: Ping /api/watch/cron-maintenance-all
        run: |
          URL="$BASE_URL/api/watch/cron-maintenance-all?token=$CRON_SECRET"
          for i in {1..5}; do
            RESP=$(curl -sSL -w "\n%{http_code}" "$URL")
            CODE="${RESP##*$'\n'}"; BODY="${RESP%$'\n'*}"
            echo "HTTP $CODE"; echo "$BODY"
            [[ "$CODE" =~ ^(200|202|204)$ ]] && exit 0
            sleep 10
          done
          exit 1
