name: Ping Vercel endpoints (every 5m)

on:
  schedule:
    - cron: "*/5 * * * *"   # alle 5 Minuten (UTC)
  workflow_dispatch:

jobs:
  ping:
    # falls du ein Environment-Secret nutzt, UNKOMMENTIEREN:
    # environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ext-crons-5m
      cancel-in-progress: false
    env:
      BASE_URL: "https://spotify-oauth-min-jonas-sercombes-projects.vercel.app"
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    steps:
      - name: Show context (UTC) & secret presence
        run: |
          echo "Now (UTC): $(date -u +'%Y-%m-%d %H:%M:%S')"
          if [ -z "$CRON_SECRET" ]; then
            echo "CRON_SECRET is EMPTY (check repo vs environment secrets!)"
            exit 1
          else
            echo "CRON_SECRET is set (masked)."
          fi

      - name: Ping /api/followers/cron-refresh-all (x-service-key)
        run: |
          URL="$BASE_URL/api/followers/cron-refresh-all"
          for i in {1..5}; do
            echo "Attempt $i → $URL"
            RESP=$(curl -sSL -H "x-service-key: $CRON_SECRET" -w "\n%{http_code}" "$URL")
            CODE="${RESP##*$'\n'}"
            BODY="${RESP%$'\n'*}"
            echo "HTTP $CODE"
            echo "Body:"
            echo "$BODY"
            if [[ "$CODE" =~ ^(200|202|204)$ ]]; then
              echo "Success."
              exit 0
            fi
            sleep 10
          done
          echo "Endpoint returned non-2xx after retries"; exit 1

      - name: Ping /api/watch/cron-all (x-service-key)
        run: |
          URL="$BASE_URL/api/watch/cron-all"
          for i in {1..5}; do
            echo "Attempt $i → $URL"
            RESP=$(curl -sSL -H "x-service-key: $CRON_SECRET" -w "\n%{http_code}" "$URL")
            CODE="${RESP##*$'\n'}"
            BODY="${RESP%$'\n'*}"
            echo "HTTP $CODE"
            echo "Body:"
            echo "$BODY"
            if [[ "$CODE" =~ ^(200|202|204)$ ]]; then
              echo "Success."
              exit 0
            fi
            sleep 10
          done
          echo "Endpoint returned non-2xx after retries"; exit 1
