name: Ping Vercel endpoints (every 5m)

on:
  schedule:
    - cron: "*/5 * * * *"   # alle 5 Minuten (UTC)
  workflow_dispatch:

jobs:
  ping:
    # falls du ein Environment-Secret (nicht Repo-Secret) nutzt, kommentiere die nächste Zeile ein:
    # environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ext-crons-5m
      cancel-in-progress: false
    env:
      BASE_URL: "https://spotify-oauth-min-jonas-sercombes-projects.vercel.app"
      CRON_SECRET: ${{ secrets.CRON_SECRET }}
    steps:
      - name: Check secret
        run: |
          if [ -z "$CRON_SECRET" ]; then
            echo "CRON_SECRET is EMPTY (repo vs environment secrets?)"
            exit 1
          fi
          echo "CRON_SECRET is set (masked). Now: $(date -u +'%Y-%m-%d %H:%M:%S')"

      - name: Ping /api/followers/cron-refresh-all (Bearer)
        run: |
          URL="$BASE_URL/api/followers/cron-refresh-all"
          for i in {1..5}; do
            echo "Attempt $i → $URL"
            RESP=$(curl -sSL -H "Authorization: Bearer $CRON_SECRET" -w "\n%{http_code}" "$URL")
            CODE="${RESP##*$'\n'}"; BODY="${RESP%$'\n'*}"
            echo "HTTP $CODE"; echo "$BODY"
            [[ "$CODE" =~ ^(200|202|204)$ ]] && exit 0
            sleep 10
          done
          echo "Endpoint returned non-2xx after retries"; exit 1

      - name: Ping /api/watch/cron-all (Bearer)
        run: |
          URL="$BASE_URL/api/watch/cron-all"
          for i in {1..5}; do
            echo "Attempt $i → $URL"
            RESP=$(curl -sSL -H "Authorization: Bearer $CRON_SECRET" -w "\n%{http_code}" "$URL")
            CODE="${RESP##*$'\n'}"; BODY="${RESP%$'\n'*}"
            echo "HTTP $CODE"; echo "$BODY"
            [[ "$CODE" =~ ^(200|202|204)$ ]] && exit 0
            sleep 10
          done
          echo "Endpoint returned non-2xx after retries"; exit 1
