# .github/workflows/ping-every-5m.yml
name: Ping Vercel endpoints (every 5m)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ext-crons-5m
      cancel-in-progress: false
    env:
      BASE_URL: "https://spotify-oauth-min-jonas-sercombes-projects.vercel.app"
    steps:
      - name: Ping /api/followers/cron-refresh-all
        run: |
          for i in {1..3}; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" "$BASE_URL/api/followers/cron-refresh-all") || true
            echo "HTTP $CODE"
            [ "$CODE" = "200" ] && exit 0
            sleep 5
          done
          echo "Endpoint returned non-200 after retries"; exit 1

      - name: Ping /api/watch/cron-all
        run: |
          for i in {1..3}; do
            CODE=$(curl -sS -o /dev/null -w "%{http_code}" "$BASE_URL/api/watch/cron-all") || true
            echo "HTTP $CODE"
            [ "$CODE" = "200" ] && exit 0
            sleep 5
          done
          echo "Endpoint returned non-200 after retries"; exit 1
